version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: myapp-backend
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    # ports:
    #   - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
      - tmp-data:/app/tmp
      - log-data:/app/log
    tty: true # ポート待ち受けにしてない場合でもコンテナが終了しないように
    stdin_open: true # ttyとセット  
  db:
    container_name: myapp-db
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: myapp-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - tmp-data:/app/tmp
    tty: true
    stdin_open: true
    depends_on:
      - backend
  front:
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    container_name: myapp-front
    # ports:
    #    - '8080:8080'
    volumes:
      - ./vue:/app:cached # cached(オプション)
    stdin_open: true
    tty: true
    command: sh -c "cd assets && npm install && npm run serve" # ここのコメントアウトを外す。
volumes:
  bundle:
  tmp-data:
  log-data:
  db-data: