version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - ./api/environments/db.env
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
      - tmp-data:/app/tmp
      - log-data:/app/log
    tty: true # ポート待ち受けにしてない場合でもコンテナが終了しないように
    stdin_open: true # ttyとセット  
  db:
    image: mysql:5.7
    env_file:
      - ./api/environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '9000:80'
    volumes:
      - ./data/www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - tmp-data:/app/tmp
    tty: true
    stdin_open: true
    depends_on:
      - web
  vue:
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    volumes:
      - ./data/www:/app
    tty: true
volumes:
  bundle:
  tmp-data:
  log-data:
  db-data: